config/routes.rb
Rails.application.routes.draw do
  
  
  root 'sessions#index', as: :home_page
  get 'login', to: 'sessions#new', as: :login_path
  post 'login', to: 'sessions#create', as: :login_try_path
  get 'logout', to: 'sessions#logout', as: :logout_path
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :languages
  resources :topics
  resources :versions
  resources :doc_entries
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc_entry.rb
class DocEntry < ApplicationRecord
  belongs_to :language
  belongs_to :topic
  belongs_to :version
end

app/models/language.rb
class Language < ApplicationRecord
  validates :name, presence: true, length: {minimum: 4}
  validates :slug, presence: true, length: {minimum: 2}
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :slug, presence: true, length: {minimum: 3}
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/models/version.rb
class Version < ApplicationRecord
  validates :name, presence: true, format: {with: /\A\d+(\.\d+)*(\-[a-z]+\d*)?\z/}
  validates :github_tag, format: {with: /\A\d+\.\d+\.\d+\z/}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :check_authorization
  helper_method :logged_in?
  helper_method :current_user
  helper_method :admin?
rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def current_user
    if !session[:user_id].nil?
      User.find(session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def admin?
    current_user && current_user.role == 100
  end

  def check_authorization
    redirect_to :login_path unless logged_in?
  end

  @private
  def record_not_found
    render 'layouts/404'
  end
end

app/controllers/doc_entries_controller.rb
class DocEntriesController < ApplicationController
  def new
    @doc = DocEntry.new(language_id: 1)
    @langs = Language.all
    @versions = Version.all
    @topics = Topic.all
  end

  def index
    @docs = DocEntry.all
  end

  def show
    @doc = DocEntry.find(params[:id])
  end

  def edit
    @langs = Language.all
    @versions = Version.all
    @topics = Topic.all
    @doc = DocEntry.find(params[:id])
  end
  
  def update
    @doc = DocEntry.find(params[:id])
    data = params.require(:doc_entry).permit!
    if @doc.update(data)
      flash.notice = "Doc successfully edited"
      redirect_to @doc
    else
      @langs = Language.all
      @versions = Version.all
      @topics = Topic.all
      render edit_doc_entries_path(@doc)
    end 
    
  end

  def create
     
    data = params.require(:doc_entry).permit!
    @doc = DocEntry.new(data)
    if @doc.save
      flash.notice = "Doc successfully saved"
      redirect_to @doc
    else
      @langs = Language.all
      @versions = Version.all
      @topics = Topic.all
      render new_doc_entry_path(@doc)
    end 
  end

  def destroy
    @doc = DocEntry.find(params[:id])
    @doc.destroy
    redirect_to 'index'
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  def index
    @lang = Language.new
    @langs = Language.all
  end

  def create
    name = params[:language][:name]
    slug = params[:language][:slug]
    @lang = Language.new(name: name, slug: slug)
    if @lang.save
      redirect_to @lang
    else
      @langs = Language.all
      render 'index'
    end
  end 

  def show
    @lang = Language.find(params[:id])
  end

  def edit
    @lang = Language.find(params[:id])
  end

  def update
    @lang = Language.find(params[:id])
    @lang.name = params[:language][:name]
    @lang.slug = params[:language][:slug]
    if @lang.save
      redirect_to @lang
    else
      
      render 'edit'
    end
  end

  def destroy
    @lang = Language.find(params[:id])
    lang_name = @lang.name
    @lang.destroy
    if @lang.destroyed?
      flash.notice = "The language #{lang_name} was destroyed"
    else
      flash.alert = "The language #{lang_name} was not destroyed properly"
    end
    redirect_to languages_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :check_authorization, only: [:new, :create]
  def index
    @user = User.find(session[:user_id])
  end
  
  def new
    @user = User.new
  end

  def logout
    session[:user_id] = nil
    redirect_to :login_path
  end

  def create
    post_data = params.require(:user).permit(:username, :password)
    @user = User.find_by(username: post_data[:username])
    if @user && @user.authenticate(post_data[:password])
      session[:user_id] = @user.id
      redirect_to :home_page
    else
      flash.notice = "User not found! Can't log you in."
      redirect_to :login_path
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topic = Topic.new
    @topics = Topic.all
  end

  def create
    slug = params[:topic][:slug]
    metadata = params[:topic][:metadata]
    @topic = Topic.new(slug: slug, metadata: metadata)
    if @topic.save
      redirect_to @topic
    else
      @topics = Topic.all
      render 'index'
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    slug = params[:topic][:slug]
    metadata = params[:topic][:metadata]
    @topic = Topic.find(params[:id])
    @topic.slug = slug
    @topic.metadata = metadata
    if @topic.save
      redirect_to @topic
    else
      @topics = Topic.all
      render 'index'
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    alert = "Topic #{@topic.slug} destroyed"
    @topic.destroy
    @topics = Topic.all
    flash.alert = alert
    redirect_to 'index'
  end

  def show
    @topic = Topic.find(params[:id])

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  def index
    @versions = Version.all
    @version = Version.new
  end

  def update
    chlog = params[:version][:changelog]
    name = params[:version][:name]
    gh_tag = params[:version][:github_tag]
    @version = Version.find(params[:id])
    @version.changelog = chlog
    @version.name = name
    @version.github_tag = gh_tag
    if @version.save
      flash.notice = "Version #{name} was successfully edited"
      redirect_to @version
    else
      @versions = Version.all
      render 'index'
    end
  end

  def destroy
    @version = Version.find(params[:id])
    msg = "Version #{@version.name} destroyed"
    @version.destroy
    flash.alert = msg
    redirect_to 'index'
  end

  def edit
    @version = Version.find(params[:id])
    
  end

  def show
    @version = Version.find(params[:id])
  end

  def create
    name = params[:version][:name]
    tag = params[:version][:github_tag]
    changelog = params[:version][:changelog]
    @version = Version.new(name: name, github_tag: tag, changelog: changelog)
    if @version.save
      redirect_to @version
    else
      @versions = Version.all
      render 'index'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doc_entries_helper.rb
module DocEntriesHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/doc_entries/_form.html.erb
<div class="row">
    
    <div class="card" style="width: 100%">
      <div class="card-header">
        <h4>Create new doc entry</h4>
      </div>
      <div class="card-body">
        <div>
          <%= form_with model: @doc, local: true do |form| %>
            <div class="row">
              <div class="col-lg-4">
                <div class="form-group">
                  <%= form.label 'Language' %><br>
                  <select class="form-control" name="doc_entry[language_id]">
                    <% @langs.each do |item| %>
                      <%= tag.option item.name, selected: (item.id == @doc.language_id), value: item.id %>
                    <% end %>
                  </select>
                </div>
              </div>
              <div class="col-lg-4">
                <div class="form-group">
                  <%= form.label 'Topic' %><br>
                  <select class="form-control"  name="doc_entry[topic_id]">
                    <% @topics.each do |item| %>
                      <%= tag.option item.slug, selected: (item.id == @doc.topic_id), value: item.id %>
                    <% end %>
                  </select>
                </div>
              </div>
              <div class="col-lg-4">
                <div class="form-group">
                  <%= form.label 'Version' %><br>
                  <select class="form-control" name="doc_entry[version_id]">
                    <% @versions.each do |item| %>
                      <option value="<%= item.id %>"><%= item.name %></option>
                    <% end %>
                  </select>
                </div>
              </div>
            </div>
            <div class="form-group">
              <%= form.label :title %><br>
              <%= form.text_field :title, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :abstract %><br>
              <%= form.text_field :abstract, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :content %><br>
              <%= form.text_area :content, class: "form-control" %>
            </div>
            <div class="row">
              <div class="col-lg-4">
                <div class="form-group">
                  <%= form.label 'After' %><br>
                  <select class="form-control">
                    <option value="0">First</option>
                    <% @topics.each do |item| %>
                      <option value="<%= item.id %>"><%= item.slug %></option>
                    <% end %>
                  </select>
                </div>
              </div>
              <div class="col-lg-4">
                <div class="form-group">
                  <%= form.label 'Ref older topic' %><br>
                  <select class="form-control">
                    <option value="0">Root</option>
                    <% @topics.each do |item| %>
                      <option value="<%= item.id %>"><%= item.slug %></option>
                    <% end %>
                  </select>
                </div>
              </div>
              <div class="col-lg-4">
                <div class="form-group">
                  <%= form.label 'Ref older version' %><br>
                  <select class="form-control">
                    <option value="0">First</option>
                    <% @versions.each do |item| %>
                      <option value="<%= item.id %>"><%= item.name %></option>
                    <% end %>
                  </select>
                </div>
              </div>
            </div>
            <%= form.submit 'Save', class: "btn btn-primary"%>
          <% end %>
        </div>
      </div>
  
</div>

app/views/doc_entries/create.html.erb
<h1>DocEntries#create</h1>
<p>Find me in app/views/doc_entries/create.html.erb</p>

app/views/doc_entries/destroy.html.erb
<h1>DocEntries#destroy</h1>
<p>Find me in app/views/doc_entries/destroy.html.erb</p>

app/views/doc_entries/edit.html.erb
<h3>Edit documentation entry #<%= @doc.id %></h3>

<%= render partial: 'layouts/errors', locals: {model: @doc} %>  
<%= render partial: 'form' %>

app/views/doc_entries/index.html.erb
<h3>Documentations</h3>
<div class="row">
  
  <table class="table table-bordered">
    <thead  class="thead-dark">
      <tr>
        <th>#</th>
        <th>Slug</th>
        <th>Version</th>
        <th>Abstract</th>
      </tr>
    </thead>
    <tbody>
      <% if @docs.length() > 0 %>
        <% @docs.each do |item| %>
        <tr>
          <td><%= item.id  %></td>
          <td><%= link_to item.topic.slug, doc_entry_path(item)  %></td>
          <td><%= item.version.name  %></td>
          <td><%= item.abstract  %></td>
        </tr>
        <% end %>
      <% else %>
        <tr>
          <td colspan="4">No documentations registered</td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= render partial: 'components/bs-btn', locals: {location: :new_doc_entry, qualifier: 'primary', link_text: 'Create doc entry'} %>
</div>

app/views/doc_entries/new.html.erb
<h3>New documentation entry</h3>

<%= render partial: 'layouts/errors', locals: {model: @doc} %>  
<div class="row">
    
    <div class="card" style="width: 100%">
      <div class="card-header">
        <h4>Create new doc entry</h4>
      </div>
      <div class="card-body">
        <div>
          <%= form_with model: @doc, local: true do |form| %>
            <div class="row">
              <div class="col-lg-4">
                <div class="form-group">
                  <%= form.label 'Language' %><br>
                  <select class="form-control" name="doc_entry[language_id]">
                    <% @langs.each do |item| %>
                      <option value="<%= item.id %>"><%= item.name %></option>
                    <% end %>
                  </select>
                </div>
              </div>
              <div class="col-lg-4">
                <div class="form-group">
                  <%= form.label 'Topic' %><br>
                  <select class="form-control"  name="doc_entry[topic_id]">
                    <% @topics.each do |item| %>
                      <option value="<%= item.id %>"><%= item.slug %></option>
                    <% end %>
                  </select>
                </div>
              </div>
              <div class="col-lg-4">
                <div class="form-group">
                  <%= form.label 'Version' %><br>
                  <select class="form-control" name="doc_entry[version_id]">
                    <% @versions.each do |item| %>
                      <option value="<%= item.id %>"><%= item.name %></option>
                    <% end %>
                  </select>
                </div>
              </div>
            </div>
            <div class="form-group">
              <%= form.label :title %><br>
              <%= form.text_field :title, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :abstract %><br>
              <%= form.text_field :abstract, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :content %><br>
              <%= form.text_area :content, class: "form-control" %>
            </div>
            <div class="row">
              <div class="col-lg-4">
                <div class="form-group">
                  <%= form.label 'After' %><br>
                  <select class="form-control">
                    <option value="0">First</option>
                    <% @topics.each do |item| %>
                      <option value="<%= item.id %>"><%= item.slug %></option>
                    <% end %>
                  </select>
                </div>
              </div>
              <div class="col-lg-4">
                <div class="form-group">
                  <%= form.label 'Ref older topic' %><br>
                  <select class="form-control">
                    <option value="0">Root</option>
                    <% @topics.each do |item| %>
                      <option value="<%= item.id %>"><%= item.slug %></option>
                    <% end %>
                  </select>
                </div>
              </div>
              <div class="col-lg-4">
                <div class="form-group">
                  <%= form.label 'Ref older version' %><br>
                  <select class="form-control">
                    <option value="0">First</option>
                    <% @versions.each do |item| %>
                      <option value="<%= item.id %>"><%= item.name %></option>
                    <% end %>
                  </select>
                </div>
              </div>
            </div>
            <%= form.submit 'Save', class: "btn btn-primary"%>
          <% end %>
        </div>
      </div>
  
</div>

app/views/doc_entries/show.html.erb
<h1><%= @doc.title %></h1>
<p><strong>Abstract: </strong><%= @doc.abstract %></p>
<p><strong>Topic: </strong><%= @doc.topic.slug %></p>
<p><strong>Language: </strong><%= @doc.language.name %></p>
<p><strong>Version: </strong><%= @doc.version.name %></p>
<div class="col-lg-12" style="margin-bottom: 10px">
  <div class="card">
    <div class="card-header">
      Content
    </div>
    <div class="card-body">
      <%= simple_format @doc.content %>
    </div>
  </div>
    
</div>
<%= link_to 'Delete this doc', doc_entry_path(@doc), method: :delete, data: { confirm: "Are you sure?"}, class: 'btn btn-danger' %>
<%= render partial: 'components/bs-btn', locals: {location: edit_doc_entry_path(@doc), link_text: 'Edit this version', qualifier: 'primary'} %>
<%= render partial: 'components/bs-btn', locals: {location: doc_entries_path, link_text: 'All doc entries', qualifier: 'primary'} %>

app/views/doc_entries/update.html.erb
<h1>DocEntries#update</h1>
<p>Find me in app/views/doc_entries/update.html.erb</p>

app/views/languages/edit.html.erb
<%= render partial: 'layouts/errors', locals: {model: @lang} %>  
<div class="row">
    
    <div class="card" style="width: 100%">
      <div class="card-header">
        <h4>Edit language <%= @lang.name %></h4>
      </div>
      <div class="card-body">
        <div>
          <%= form_with model: @lang, local: true do |form| %>
            <div class="form-group">
              <%= form.label :name %><br>
              <%= form.text_field :name, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :slug %><br>
              <%= form.text_field :slug, class: "form-control" %>
            </div>
            <%= form.submit 'Save', class: "btn btn-primary"%>
          <% end %>
        </div>
      </div>
  
</div>

app/views/languages/index.html.erb
<h3>Languages</h3>

  

<div class="row">
  
  <table class="table table-bordered">
    <thead  class="thead-dark">
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Slug</th>
      </tr>
    </thead>
    <tbody>
      <% if @langs.length() > 0 %>
        <% @langs.each do |lang| %>
        <tr>
          <td><%= lang.id  %></td>
          <td><%= link_to lang.name, language_path(lang)  %></td>
          
          <td><%= lang.slug %></td>
        </tr>
        <% end %>
      <% else %>
        <tr>
          <td colspan="3">No languages registered</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= render partial: 'layouts/errors', locals: {model: @lang} %>
<div class="row">
    <div class="card" style="width: 100%">
      <div class="card-header">
        <h4>New language</h4>
      </div>
      <div class="card-body">
        <div>
          <%= form_with model: @lang, local: true do |form| %>
            <div class="form-group">
              <%= form.label :name %><br>
              <%= form.text_field :name, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :slug %><br>
              <%= form.text_field :slug, class: "form-control" %>
            </div>
            <%= form.submit 'Save', class: "btn btn-primary"%>
          <% end %>
        </div>
      </div>
  
</div>

app/views/languages/show.html.erb
<h5>Language</h5>
<h3><%= @lang.name %></h3>
<p><strong>Slug: </strong><%= @lang.slug %></p>
<%= link_to 'Delete this language', language_path(@lang), method: :delete, data: { confirm: "Are you sure?"}, class: 'btn btn-danger' %>
<%= render partial: 'components/bs-btn', locals: {location: edit_language_path(@lang), link_text: 'Edit this language', qualifier: 'primary'} %>
<%= render partial: 'components/bs-btn', locals: {location: languages_path, link_text: 'All languages', qualifier: 'primary'} %>

app/views/layouts/_admin_nav.html.erb
<% if admin? %>
  <li class="nav-item">
    <a class="nav-link" href="<%= url_for languages_path %>">Languages</a>
  </li>
  <li>
    <a class="nav-link" href="<%= url_for topics_path %>">Topics</a>
  </li>
  <li>
    <a class="nav-link" href="<%= url_for versions_path %>">Versions</a>
  </li>
  <li>
    <a class="nav-link" href="<%= url_for doc_entries_path %>">Documentations</a>
  </li>
<% end %>

app/views/layouts/_errors.html.erb
<div class="row">
  <div class="col-12">
    <% if model.errors.any? %>
      <div id="error_explanation">
        <% model.errors.full_messages.each do |msg| %>
          
          <div class="alert alert-danger" role="alert"><%= msg %></div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UltraGen docs Admin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js" integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark" style="margin-bottom: 20px">
      <ul class="navbar-nav">
        
        <% if logged_in? %>
          <li class="nav-item">
            <a class="nav-link" href="<%= url_for :logout_path %>">Logout</a>
          </li>
          <%= render partial: 'layouts/admin_nav' %>
        <% else  %>
          <li class="nav-item">
            <a class="nav-link" target="_blank" href="https://github.com/alantelles/ultragen">GitHub</a>
          </li>
        <% end %>
          
        
          
        
      </ul>
    </nav>
    <div class='container'>
      <div class="row">
      <% flash.each do |type, msg| %>
        <div class="alert alert-primary" style="width: 100%">
          <%= msg %>
        </div>
      <% end %>
      </div>
      
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/topics/edit.html.erb
<%= render partial: 'layouts/errors', locals: {model: @topic} %>
<div class="row">
    <div class="card" style="width: 100%">
      <div class="card-header">
        <h4>Edit topic <%= @topic.slug %></h4>
      </div>
      <div class="card-body">
        <div>
          <%= form_with model: @topic, local: true do |form| %>
            <div class="form-group">
              <%= form.label :slug %><br>
              <%= form.text_field :slug, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :metadata %><br>
              <%= form.text_area :metadata, class: "form-control" %>
            </div>
            <%= form.submit 'Save', class: "btn btn-primary"%>
          <% end %>
        </div>
      </div>
  
</div>

app/views/topics/index.html.erb
<h3>Topics</h3>
<div class="row">
  
  <table class="table table-bordered">
    <thead  class="thead-dark">
      <tr>
        <th>#</th>
        <th>Slug</th>
        <th>Metadata</th>
      </tr>
    </thead>
    <tbody>
      <% if @topics.length() > 0 %>
        <% @topics.each do |topic| %>
        <tr>
          <td><%= topic.id  %></td>
          <td><%= link_to topic.slug, topic_path(topic)  %></td>
          <td><pre><%= topic.metadata %></pre></td>
        </tr>
        <% end %>
      <% else %>
        <tr>
          <td colspan="3">No topics registered</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= render partial: 'layouts/errors', locals: {model: @topic} %>
<div class="row">
    <div class="card" style="width: 100%">
      <div class="card-header">
        <h4>New topic</h4>
      </div>
      <div class="card-body">
        <div>
          <%= form_with model: @topic, local: true do |form| %>
            <div class="form-group">
              <%= form.label :slug %><br>
              <%= form.text_field :slug, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :metadata %><br>
              <%= form.text_area :metadata, class: "form-control" %>
            </div>
            <%= form.submit 'Save', class: "btn btn-primary"%>
          <% end %>
        </div>
      </div>
  
</div>

app/views/topics/show.html.erb
<h5>Topic</h5>
<h3><%= @topic.slug %></h3>
<p><strong>Metadata: </strong></p>
<div class="card" style="margin-bottom: 10px">
  <div class="card-body">
  <pre><%= @topic.metadata %></pre>
  </div>
</div>
<%= link_to 'Delete this topic', topic_path(@topic), method: :delete, data: { confirm: "Are you sure?"}, class: 'btn btn-danger' %>
<%= render partial: 'components/bs-btn', locals: {location: edit_topic_path(@topic), link_text: 'Edit this topic', qualifier: 'primary'} %>
<%= render partial: 'components/bs-btn', locals: {location: topics_path, link_text: 'All topics', qualifier: 'primary'} %>

app/views/versions/create.html.erb
<h1>Versions#create</h1>
<p>Find me in app/views/versions/create.html.erb</p>

app/views/versions/edit.html.erb
<%= render partial: 'layouts/errors', locals: {model: @version} %>
<div class="row">
    <div class="card" style="width: 100%">
      <div class="card-header">
        <h4>Edit version <%= @version.name %></h4>
      </div>
      <div class="card-body">
        <div>
          <%= form_with model: @version, local: true do |form| %>
            <div class="form-group">
              <%= form.label :name %><br>
              <%= form.text_field :name, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :github_tag %><br>
              <%= form.text_field :github_tag, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :changelog %><br>
              <%= form.text_area :changelog, class: "form-control" %>
            </div>
            <%= form.submit 'Save', class: "btn btn-primary"%>
          <% end %>
        </div>
      </div>
  
</div>

app/views/versions/index.html.erb
<h3>Versions</h3>
<div class="row">

  <table class="table table-bordered">
    <thead  class="thead-dark">
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Github tag</th>
      </tr>
    </thead>
    <tbody>
      <% if @versions.length() > 0 %>
        <% @versions.each do |version| %>
        <tr>
          <td><%= version.id  %></td>
          <td><%= link_to version.name, version_path(version)  %></td>
          <td><%= version.github_tag  %></td>
        </tr>
        <% end %>
      <% else %>
        <tr>
          <td colspan="3">No versions registered</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= render partial: 'layouts/errors', locals: {model: @version} %>
<div class="row">
    <div class="card" style="width: 100%">
      <div class="card-header">
        <h4>New version</h4>
      </div>
      <div class="card-body">
        <div>
          <%= form_with model: @version, local: true do |form| %>
            <div class="form-group">
              <%= form.label :name %><br>
              <%= form.text_field :name, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :github_tag %><br>
              <%= form.text_field :github_tag, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :changelog %><br>
              <%= form.text_area :changelog, class: "form-control" %>
            </div>
            <%= form.submit 'Save', class: "btn btn-primary"%>
          <% end %>
        </div>
      </div>
  
</div>

app/views/versions/show.html.erb
<h5>Version</h5>

<h3><%= @version.name %></h3>
<p><strong>Github tag: </strong><%= @version.github_tag %></p>
<p><strong>Changelog: </strong></p>
<div class="card" style="margin-bottom: 10px">
  <div class="card-body">
  <pre><%= @version.changelog %></pre>
  </div>
</div>
<%= link_to 'Delete this version', version_path(@version), method: :delete, data: { confirm: "Are you sure?"}, class: 'btn btn-danger' %>
<%= render partial: 'components/bs-btn', locals: {location: edit_version_path(@version), link_text: 'Edit this version', qualifier: 'primary'} %>
<%= render partial: 'components/bs-btn', locals: {location: versions_path, link_text: 'All versions', qualifier: 'primary'} %>

app/views/versions/update.html.erb
<h1>Versions#update</h1>
<p>Find me in app/views/versions/update.html.erb</p>